version: "3.6"
services:

  monolito:
    build: ./monolito
    ports:
      - "8081:8081"
    environment:
      notificador.uri: http://msnotificador:8083

  mspedido:
    build: ./microservicio-pedido
    ports:
      - "8082:8082"
    environment:
      monolito.uri: http://monolito:8081

  msnotificador:
    build: ./microservicio-notificacion
    ports:
      - "8083:8083"

  apigateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      monolito.uri: monolito
      monolito.pot: 8081
      mspedido.uri: mspedido
      mspedido.pot: 8082
      msnotificador.uri: msnotificador
      msnotificador.pot: 8083